definitions:
  SongCreate:
    properties:
      group:
        type: string
      link:
        type: string
      releaseDate:
        type: string
      song:
        type: string
      text:
        type: string
    required:
    - group
    - song
    type: object
  SongDescription:
    properties:
      group:
        type: string
      link:
        type: string
      releaseDate:
        type: string
      song:
        type: string
    type: object
  SongUpdate:
    properties:
      group:
        type: string
      link:
        type: string
      releaseDate:
        type: string
      song:
        type: string
      text:
        type: string
    required:
    - group
    - song
    type: object
info:
  contact: {}
  description: This is a simple API for managing home music library.
  title: Home Music Library API
  version: "1.0"
paths:
  /song:
    post:
      consumes:
      - application/json
      description: Создает новую песню на основе предоставленных входных данных
      operationId: SongCreate
      parameters:
      - description: Входные данные для создания песни
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/SongCreate'
      produces:
      - application/json
      responses:
        "200":
          description: Ok
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Создание песни
  /song/:
    delete:
      consumes:
      - application/json
      description: Удаляет песню по указанному идентификатору
      operationId: SongDelete
      parameters:
      - in: query
        name: group
        required: true
        type: string
      - in: query
        name: song
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Ok
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Удаление песни
    put:
      consumes:
      - application/json
      description: Обновляет песню с таким же названием и группой
      parameters:
      - description: Входные данные о песне
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/SongUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: Ok
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Обновляет песню
  /song/info:
    get:
      consumes:
      - application/json
      description: Возвращает информацию о песни на основе входных данных
      operationId: SongInfo
      parameters:
      - in: query
        name: group
        required: true
        type: string
      - in: query
        name: song
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Ok
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Получение информации о песни
  /song/search:
    get:
      description: Поиск песни по заданным параметрам
      parameters:
      - in: query
        name: group
        type: string
      - in: query
        name: link
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: pageSize
        type: integer
      - in: query
        name: releaseDate
        type: string
      - in: query
        name: song
        type: string
      - in: query
        name: text
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/SongDescription'
            type: array
      summary: Поиск песни
  /song/verses:
    get:
      description: Получение куплетов песни с пагинацией
      parameters:
      - in: query
        name: group
        required: true
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: pageSize
        type: integer
      - in: query
        name: song
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Ok
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Получение куплетов песни
swagger: "2.0"
